server.port=8081
spring.application.name=ms-rutaexpress-bff

# URL del microservicio backend de Shipments
shipments.service.url=http://localhost:8080/api/envios

# Configuracion de Azure AD / Entra ID
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/d4e45c2c-5598-4953-9517-f1c5f09d4eb1/v2.0
spring.security.oauth2.resourceserver.jwt.audience=api://c515cc67-aed4-4210-89f0-433271797592

catalog.service.url=http://localhost:8083/api/catalog